spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:db/schema-h2.sql
    #    data: classpath:db/data-h2.sql
    url: jdbc:mysql://www.starix.top:3306/weixin_mp?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xxxx
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

server:
  # 这个用作https端口
  port: 9800
  #这个字段属于自定义的，用于http端口
  custom:
    httpPort: 9801
  ssl:
    key-store: classpath:3262598_starix.top.pfx
    key-store-password: Pr1ifVXd
    key-store-type: PKCS12


gdou:
#  jw-url: http://210.38.137.77:8016
  webvpn-url: https://webvpn.gdou.edu.cn
  webvpn-username: xxxx
  webvpn-password: xxxx
  jw-url: https://webvpn.gdou.edu.cn/http/77726476706e69737468656265737421a2a611d2746826012d5fc7f4cc
